/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */
package matterdb.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 1;
  /** RegularExpression Id. */
  int SELECT = 7;
  /** RegularExpression Id. */
  int FROM = 8;
  /** RegularExpression Id. */
  int WHERE = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int CREATE = 11;
  /** RegularExpression Id. */
  int DATABASE = 12;
  /** RegularExpression Id. */
  int DROP = 13;
  /** RegularExpression Id. */
  int USE = 14;
  /** RegularExpression Id. */
  int TABLE = 15;
  /** RegularExpression Id. */
  int ALTER = 16;
  /** RegularExpression Id. */
  int ADD = 17;
  /** RegularExpression Id. */
  int EXIT = 18;
  /** RegularExpression Id. */
  int INSERT = 19;
  /** RegularExpression Id. */
  int INTO = 20;
  /** RegularExpression Id. */
  int VALUES = 21;
  /** RegularExpression Id. */
  int UPDATE = 22;
  /** RegularExpression Id. */
  int SET = 23;
  /** RegularExpression Id. */
  int DELETE = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int FLOAT = 26;
  /** RegularExpression Id. */
  int CHAR = 27;
  /** RegularExpression Id. */
  int VARCHAR = 28;
  /** RegularExpression Id. */
  int SEMICOLON = 29;
  /** RegularExpression Id. */
  int QUOTE = 30;
  /** RegularExpression Id. */
  int DOT = 31;
  /** RegularExpression Id. */
  int COMMA = 32;
  /** RegularExpression Id. */
  int OPENBRACKET = 33;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 34;
  /** RegularExpression Id. */
  int NAME = 35;
  /** RegularExpression Id. */
  int CONDITIONS = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"AND\"",
    "\"CREATE\"",
    "\"DATABASE\"",
    "\"DROP\"",
    "\"USE\"",
    "\"TABLE\"",
    "\"ALTER\"",
    "\"ADD\"",
    "\".EXIT\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"UPDATE\"",
    "\"SET\"",
    "\"DELETE\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"varchar\"",
    "\";\"",
    "<QUOTE>",
    "\".\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<NAME>",
    "<CONDITIONS>",
  };

}
